import type { Profile, Capsule, Story, Conversation, Message, Notification, FollowRequest } from '../types';

export const DEMO_USER_ID = 'demo-user-001';

export const demoProfiles: Profile[] = [
  {
    id: DEMO_USER_ID,
    username: 'alexrivera',
    full_name: 'Alex Rivera',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alexrivera&backgroundColor=b6e3f4',
    bio: 'Capturing moments, unlocking memories ✨ | Building the future one day at a time',
    is_private: false,
    capsule_count: 12,
    follower_count: 248,
    following_count: 131,
    streak: 7,
    badges: ['early_adopter', 'memory_maker', 'social_butterfly'],
    created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'demo-user-002',
    username: 'sarahchen',
    full_name: 'Sarah Chen',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarahchen&backgroundColor=ffd5dc',
    bio: 'Photography 📷 | Travel ✈️ | Coffee ☕',
    is_private: false,
    capsule_count: 8,
    follower_count: 512,
    following_count: 204,
    streak: 14,
    badges: ['early_adopter', 'photographer'],
    created_at: '2025-02-01T09:00:00Z',
  },
  {
    id: 'demo-user-003',
    username: 'marcusj',
    full_name: 'Marcus Johnson',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcusj&backgroundColor=c0aede',
    bio: 'Music producer 🎵 | Coffee addict | Creating something every day',
    is_private: false,
    capsule_count: 5,
    follower_count: 189,
    following_count: 97,
    streak: 3,
    badges: ['music_lover'],
    created_at: '2025-03-10T14:00:00Z',
  },
  {
    id: 'demo-user-004',
    username: 'emmaw',
    full_name: 'Emma Wilson',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emmaw&backgroundColor=d1f0d1',
    bio: 'Writer & dreamer 📝 | Nature lover 🌿',
    is_private: true,
    capsule_count: 15,
    follower_count: 76,
    following_count: 54,
    streak: 21,
    badges: ['writer', 'streak_master'],
    created_at: '2025-01-28T11:00:00Z',
  },
  {
    id: 'demo-user-005',
    username: 'jt_creates',
    full_name: 'Jake Torres',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jt_creates&backgroundColor=ffdfbf',
    bio: 'Designer & creative director | Making things beautiful',
    is_private: false,
    capsule_count: 22,
    follower_count: 1204,
    following_count: 312,
    streak: 45,
    badges: ['designer', 'streak_master', 'early_adopter'],
    created_at: '2025-01-01T08:00:00Z',
  },
];

export const demoCapsules: Capsule[] = [
  {
    id: 'capsule-001',
    user_id: DEMO_USER_ID,
    title: 'Summer 2025 Memories',
    message: 'This summer was absolutely magical. We went to the beach, laughed until we cried, and made memories I\'ll treasure forever. To future me: remember how happy you were in this moment.',
    unlock_date: '2026-01-01T00:00:00Z',
    visibility: 'public',
    tags: ['summer', 'memories', 'friends', 'beach'],
    location: 'Santa Monica, CA',
    created_at: '2025-07-15T10:00:00Z',
    profiles: demoProfiles[0],
    capsule_media: [
      {
        id: 'media-001',
        capsule_id: 'capsule-001',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        created_at: '2025-07-15T10:00:00Z',
      },
    ],
  },
  {
    id: 'capsule-002',
    user_id: DEMO_USER_ID,
    title: 'Letter to Future Me — 2027',
    message: 'Hey future Alex, I wonder what you\'re doing right now. I hope you\'ve achieved everything you set out to do. Remember that you had dreams and the courage to pursue them.',
    unlock_date: '2027-07-07T00:00:00Z',
    visibility: 'private',
    tags: ['personal', 'future', 'goals'],
    location: null,
    created_at: '2026-07-07T09:00:00Z',
    profiles: demoProfiles[0],
  },
  {
    id: 'capsule-003',
    user_id: DEMO_USER_ID,
    title: 'New Year Thoughts 2026',
    message: 'Starting 2026 with so much hope. My resolutions: be kinder, work smarter, and cherish every small moment. Looking back at 2025, I grew so much.',
    unlock_date: '2026-06-01T00:00:00Z',
    visibility: 'friends',
    tags: ['newyear', 'goals', '2026'],
    location: 'New York, NY',
    created_at: '2026-01-01T00:01:00Z',
    profiles: demoProfiles[0],
  },
  {
    id: 'capsule-004',
    user_id: DEMO_USER_ID,
    title: 'My First Apartment',
    message: 'Just signed the lease on my first solo apartment! Tiny but mine. I painted the kitchen yellow and hung fairy lights everywhere. This is the beginning of something.',
    unlock_date: '2027-01-01T00:00:00Z',
    visibility: 'friends',
    tags: ['milestone', 'apartment', 'independence'],
    location: 'Brooklyn, NY',
    created_at: '2026-04-15T15:00:00Z',
    profiles: demoProfiles[0],
    capsule_media: [
      {
        id: 'media-002',
        capsule_id: 'capsule-004',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
        created_at: '2026-04-15T15:00:00Z',
      },
    ],
  },
  {
    id: 'capsule-005',
    user_id: 'demo-user-002',
    title: 'Tokyo Trip Memories',
    message: 'Three weeks in Japan changed everything. The food, the people, the temples at sunrise. I want to remember every single detail of this trip.',
    unlock_date: '2026-03-01T00:00:00Z',
    visibility: 'public',
    tags: ['travel', 'japan', 'tokyo', 'adventure'],
    location: 'Tokyo, Japan',
    created_at: '2025-10-20T08:00:00Z',
    profiles: demoProfiles[1],
    capsule_media: [
      {
        id: 'media-003',
        capsule_id: 'capsule-005',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
        created_at: '2025-10-20T08:00:00Z',
      },
    ],
  },
  {
    id: 'capsule-006',
    user_id: 'demo-user-003',
    title: 'First Album Complete 🎵',
    message: 'After 18 months of work, my first album is done. Sending this to myself to open when the album reaches 1 million plays. By the time you read this, it\'s already happened.',
    unlock_date: '2026-12-31T00:00:00Z',
    visibility: 'public',
    tags: ['music', 'milestone', 'album', 'dream'],
    location: 'Los Angeles, CA',
    created_at: '2026-05-01T12:00:00Z',
    profiles: demoProfiles[2],
  },
  {
    id: 'capsule-007',
    user_id: 'demo-user-005',
    title: 'Design Portfolio 2025',
    message: 'Documenting my best work from this year. The brand redesigns, the app UI work, the poster series. So proud of how my style evolved.',
    unlock_date: '2026-06-15T00:00:00Z',
    visibility: 'public',
    tags: ['design', 'portfolio', 'creative'],
    location: 'San Francisco, CA',
    created_at: '2025-12-31T23:00:00Z',
    profiles: demoProfiles[4],
    capsule_media: [
      {
        id: 'media-004',
        capsule_id: 'capsule-007',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
        created_at: '2025-12-31T23:00:00Z',
      },
    ],
  },
];

const now = new Date();
const addHours = (h: number) => new Date(now.getTime() + h * 3600000).toISOString();
const subtractHours = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();

export const demoStories: Story[] = [
  {
    id: 'story-001',
    user_id: 'demo-user-002',
    content_url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600',
    content_type: 'photo',
    duration_hours: 24,
    expires_at: addHours(22),
    created_at: subtractHours(2),
    profiles: demoProfiles[1],
  },
  {
    id: 'story-002',
    user_id: 'demo-user-003',
    content_url: null,
    content_type: 'text',
    text_content: '🎵 New track dropping tonight! Been working on this one for weeks...',
    duration_hours: 12,
    expires_at: addHours(11),
    created_at: subtractHours(1),
    profiles: demoProfiles[2],
  },
  {
    id: 'story-003',
    user_id: 'demo-user-005',
    content_url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600',
    content_type: 'photo',
    duration_hours: 48,
    expires_at: addHours(46),
    created_at: subtractHours(2),
    profiles: demoProfiles[4],
  },
];

export const demoConversations: Conversation[] = [
  {
    id: 'conv-001',
    created_at: '2026-07-01T10:00:00Z',
    updated_at: subtractHours(1),
    other_user: demoProfiles[1],
    last_message: {
      id: 'msg-010',
      conversation_id: 'conv-001',
      sender_id: 'demo-user-002',
      content: 'That capsule you shared was so sweet! 😊',
      created_at: subtractHours(1),
      read_at: null,
    },
    unread_count: 2,
  },
  {
    id: 'conv-002',
    created_at: '2026-06-20T08:00:00Z',
    updated_at: subtractHours(5),
    other_user: demoProfiles[2],
    last_message: {
      id: 'msg-020',
      conversation_id: 'conv-002',
      sender_id: 'demo-user-003',
      content: 'Have you set up your new year\'s capsule yet?',
      created_at: subtractHours(5),
      read_at: subtractHours(4),
    },
    unread_count: 0,
  },
];

export const demoMessages: Record<string, Message[]> = {
  'conv-001': [
    {
      id: 'msg-001',
      conversation_id: 'conv-001',
      sender_id: DEMO_USER_ID,
      content: 'Hey Sarah! Did you see the new capsule I posted?',
      created_at: subtractHours(3),
      read_at: subtractHours(2),
    },
    {
      id: 'msg-002',
      conversation_id: 'conv-001',
      sender_id: 'demo-user-002',
      content: 'Just saw it! Those summer photos are incredible 😍',
      created_at: subtractHours(2.5),
      read_at: subtractHours(2),
    },
    {
      id: 'msg-003',
      conversation_id: 'conv-001',
      sender_id: DEMO_USER_ID,
      content: 'Thanks! It was such an amazing trip. We should do something like that again.',
      created_at: subtractHours(2),
      read_at: subtractHours(1.5),
    },
    {
      id: 'msg-004',
      conversation_id: 'conv-001',
      sender_id: 'demo-user-002',
      content: 'That capsule you shared was so sweet! 😊',
      created_at: subtractHours(1),
      read_at: null,
    },
  ],
  'conv-002': [
    {
      id: 'msg-011',
      conversation_id: 'conv-002',
      sender_id: 'demo-user-003',
      content: 'Yo! Working on something new 🎵',
      created_at: subtractHours(8),
      read_at: subtractHours(7),
    },
    {
      id: 'msg-012',
      conversation_id: 'conv-002',
      sender_id: DEMO_USER_ID,
      content: 'No way! What genre this time?',
      created_at: subtractHours(7),
      read_at: subtractHours(6),
    },
    {
      id: 'msg-013',
      conversation_id: 'conv-002',
      sender_id: 'demo-user-003',
      content: 'Something between lo-fi and electronic. Hard to describe but it slaps.',
      created_at: subtractHours(6),
      read_at: subtractHours(5.5),
    },
    {
      id: 'msg-020',
      conversation_id: 'conv-002',
      sender_id: 'demo-user-003',
      content: 'Have you set up your new year\'s capsule yet?',
      created_at: subtractHours(5),
      read_at: subtractHours(4),
    },
  ],
};

export const demoNotifications: Notification[] = [
  {
    id: 'notif-001',
    user_id: DEMO_USER_ID,
    type: 'follow',
    title: 'New follower',
    body: 'Sarah Chen started following you',
    read: false,
    created_at: subtractHours(2),
  },
  {
    id: 'notif-002',
    user_id: DEMO_USER_ID,
    type: 'capsule_unlock',
    title: 'Capsule unlocked! 🎉',
    body: 'Your "New Year Thoughts 2026" capsule has been unlocked',
    read: false,
    created_at: subtractHours(5),
  },
  {
    id: 'notif-003',
    user_id: DEMO_USER_ID,
    type: 'like',
    title: 'Jake Torres liked your post',
    body: '"Summer 2025 Memories" got a new like',
    read: true,
    created_at: subtractHours(24),
  },
];

export const demoFollowRequests: FollowRequest[] = [
  {
    id: 'req-001',
    requester_id: 'demo-user-004',
    target_id: DEMO_USER_ID,
    status: 'pending',
    created_at: subtractHours(3),
    profiles: demoProfiles[3],
  },
];
