import React, { useMemo, useState } from 'react';
import { Loader2 } from 'lucide-react';
import { Modal } from '../ui/Modal';
import { AVATAR_CATEGORIES, getAvatarFaces, generateAvatarSvg, svgToPngFile } from '../../lib/avatarGenerator';

interface AvatarPickerModalProps {
  isOpen: boolean;
  onClose: () => void;
  onUpload: (file: File) => Promise<{ error: string | null }>;
}

const OUTPUT_SIZE = 512;

// Ten categories x ten generated faces each — see avatarGenerator.ts for
// how every face is built (shapes and colors combined by a seed, nothing
// sourced from outside this app). Tapping a face rasterizes it to a real
// PNG and runs it through the exact same onUpload the camera/file-picker
// path already uses, so it becomes a normal profile photo — every other
// place in the app that renders an avatar needs zero changes.
export const AvatarPickerModal: React.FC<AvatarPickerModalProps> = ({ isOpen, onClose, onUpload }) => {
  const [categoryId, setCategoryId] = useState(AVATAR_CATEGORIES[0].id);
  const [pickingIndex, setPickingIndex] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const faces = useMemo(() => getAvatarFaces(categoryId), [categoryId]);

  const handlePick = async (index: number) => {
    if (pickingIndex !== null) return;
    setError(null);
    setPickingIndex(index);
    try {
      const svg = generateAvatarSvg(categoryId, index);
      const file = await svgToPngFile(svg, OUTPUT_SIZE, `avatar-${categoryId}-${index}.png`);
      const { error: uploadError } = await onUpload(file);
      if (uploadError) { setError(uploadError); setPickingIndex(null); return; }
      onClose();
    } catch {
      setError('Could not generate this avatar. Try another one.');
    } finally {
      setPickingIndex(null);
    }
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Choose an avatar" size="lg">
      <div className="flex flex-col gap-4">
        <div role="tablist" aria-label="Avatar category" className="flex gap-1.5 overflow-x-auto pb-1 -mx-1 px-1">
          {AVATAR_CATEGORIES.map(cat => (
            <button
              key={cat.id}
              type="button"
              role="tab"
              aria-selected={categoryId === cat.id}
              onClick={() => setCategoryId(cat.id)}
              className={[
                'flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-medium whitespace-nowrap flex-shrink-0 transition-colors',
                categoryId === cat.id
                  ? 'bg-gradient-to-r from-purple-600 to-blue-500 text-white shadow-sm'
                  : 'bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700',
              ].join(' ')}
            >
              <span aria-hidden="true">{cat.emoji}</span> {cat.label}
            </button>
          ))}
        </div>

        <div className="grid grid-cols-5 gap-2.5">
          {faces.map(({ index, svg }) => {
            const isPicking = pickingIndex === index;
            return (
              <button
                key={index}
                type="button"
                onClick={() => handlePick(index)}
                disabled={pickingIndex !== null}
                aria-label={`Use this ${AVATAR_CATEGORIES.find(c => c.id === categoryId)?.label ?? ''} avatar`}
                className="relative aspect-square rounded-2xl bg-gray-50 dark:bg-gray-800 border border-gray-100 dark:border-gray-700 p-1.5 hover:border-purple-300 dark:hover:border-purple-600 hover:bg-purple-50/60 dark:hover:bg-purple-950/30 transition-colors disabled:cursor-not-allowed focus-visible:ring-2 focus-visible:ring-purple-500 focus-visible:outline-none"
              >
                {/* eslint-disable-next-line react/no-danger -- self-authored, deterministic SVG markup (see avatarGenerator.ts), never user input */}
                <span className="block w-full h-full" dangerouslySetInnerHTML={{ __html: svg }} />
                {isPicking && (
                  <span className="absolute inset-0 flex items-center justify-center rounded-2xl bg-white/70 dark:bg-gray-900/70">
                    <Loader2 size={20} className="animate-spin text-purple-500" aria-hidden="true" />
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {error && <p className="text-sm text-red-500 dark:text-red-400 text-center">{error}</p>}

        <p className="text-xs text-gray-400 dark:text-gray-500 text-center">Every face here is generated by Memory Drop, not sourced from anywhere else.</p>
      </div>
    </Modal>
  );
};
